# Generated by Django 6.0.4 on 2026-05-05 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='gambar'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='courses/attachments/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Video'),
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Selesai')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diakses')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.coursecontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progres Belajar',
                'verbose_name_plural': 'Progres Belajar',
                'unique_together': {('user', 'content')},
            },
        ),
    ]
