# Generated by Django 6.0.4 on 2026-05-08 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='judul tugas')),
                ('description', models.TextField(verbose_name='deskripsi')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/attachments/', verbose_name='lampiran')),
                ('deadline', models.DateTimeField(verbose_name='batas waktu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.course', verbose_name='matkul')),
            ],
            options={
                'verbose_name': 'Tugas',
                'verbose_name_plural': 'Tugas',
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='judul pertemuan')),
                ('date', models.DateField(verbose_name='tanggal')),
                ('start_time', models.TimeField(verbose_name='waktu mulai')),
                ('end_time', models.TimeField(verbose_name='waktu selesai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.course', verbose_name='matkul')),
            ],
            options={
                'verbose_name': 'Sesi Presensi',
                'verbose_name_plural': 'Sesi Presensi',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='judul diskusi')),
                ('content', models.TextField(verbose_name='isi diskusi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to=settings.AUTH_USER_MODEL, verbose_name='penulis')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to='core.course', verbose_name='matkul')),
            ],
            options={
                'verbose_name': 'Forum Diskusi',
                'verbose_name_plural': 'Forum Diskusi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='balasan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to=settings.AUTH_USER_MODEL, verbose_name='penulis')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.forumthread', verbose_name='thread')),
            ],
            options={
                'verbose_name': 'Balasan Forum',
                'verbose_name_plural': 'Balasan Forum',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='judul kuis')),
                ('description', models.TextField(blank=True, verbose_name='deskripsi')),
                ('deadline', models.DateTimeField(verbose_name='batas waktu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.course', verbose_name='matkul')),
            ],
            options={
                'verbose_name': 'Kuis',
                'verbose_name_plural': 'Kuis',
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='pertanyaan')),
                ('points', models.IntegerField(default=10, verbose_name='poin')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz', verbose_name='kuis')),
            ],
            options={
                'verbose_name': 'Pertanyaan Kuis',
                'verbose_name_plural': 'Pertanyaan Kuis',
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='pilihan jawaban')),
                ('is_correct', models.BooleanField(default=False, verbose_name='jawaban benar')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.quizquestion', verbose_name='pertanyaan')),
            ],
            options={
                'verbose_name': 'Pilihan Kuis',
                'verbose_name_plural': 'Pilihan Kuis',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/submissions/', verbose_name='file jawaban')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='nilai')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='feedback pengajar')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment', verbose_name='tugas')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='mahasiswa')),
            ],
            options={
                'verbose_name': 'Pengumpulan Tugas',
                'verbose_name_plural': 'Pengumpulan Tugas',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Hadir'), ('late', 'Terlambat'), ('absent', 'Alpa')], default='present', max_length=10, verbose_name='status kehadiran')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='mahasiswa')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.attendancesession', verbose_name='sesi')),
            ],
            options={
                'verbose_name': 'Catatan Presensi',
                'verbose_name_plural': 'Catatan Presensi',
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='nilai')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.quiz', verbose_name='kuis')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='mahasiswa')),
            ],
            options={
                'verbose_name': 'Percobaan Kuis',
                'verbose_name_plural': 'Percobaan Kuis',
                'unique_together': {('quiz', 'student')},
            },
        ),
    ]
